pizza_pizza/urls.py
"""Defines URL patterns for pizza_pizza."""

from django.urls import path

from . import views

app_name = 'pizza_pizza'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Pizzas page
    path('pizzas/', views.pizzas, name='pizzas'),
    # A page of a single pizza's toppings
    path('pizzas/<int:pizza_id>/', views.toppings, name='pizza')
]

pp_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizza_pizza.urls'))
]

pizza_pizza/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """A pizza the user salivates about."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Toppings(models.Model):
    """The toppings that belong to the pizza."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a simple string representing the entry."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

pizza_pizza/views.py
from django.shortcuts import render
from .models import Pizza

# Create your views here.
def index(request):
    """The home page for Pizza Recipe List."""
    return render(request, 'pizza_pizza/index.html')

def pizzas(request):
    """The page that lists all tracked pizzas."""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas':pizzas}
    return render(request, 'pizza_pizza/pizzas.html', context)

def toppings(request, pizza_id):
    """The page that lists a single pizza's toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.toppings_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizza_pizza/pizza.html', context)

pizza_pizza/templates/pizza_pizza/base.html
<p>
    <a href="{% url 'pizza_pizza:index' %}">Home</a> -
    <a href="{% url 'pizza_pizza:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

pizza_pizza/templates/pizza_pizza/index.html
{% extends 'pizza_pizza/base.html' %}

{% block content %}
  <p>Pizza Pizza helps you keep track of all of your favorite pizzas.</p>
{% endblock content %}

pizza_pizza/templates/pizza_pizza/pizza.html
{% extends 'pizza_pizza/base.html' %}

{% block content %}

  <p>{{ pizza.name }} Pizza:</p>
  <p>Toppings:</p>
  <ul>
  {% for topping in toppings %}
  <li>
    <p>{{ topping.text }}</p>
  </li>
  {% empty %}
    <li>NO TOPPINGS HAVE BEEN ENTERED FOR THIS PIZZA :(</li>
  {% endfor %}
  </ul>

{% endblock content %}

pizza_pizza/templates/pizza_pizza/pizzas.html
{% extends 'pizza_pizza/base.html' %}

{% block content %}
  <p>Pizzas: (HELLO, THIS IS AWESOME)</p>
  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizza_pizza:pizza' pizza.id %}">
          {{ pizza.name }}
        </a>
      </li>
    {% empty %}
      <li>No pizzas have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}